# Development profile configuration

# Use LocalStack for AWS services in development
aws:
  region: us-east-1
  s3:
    bucket: lexygraphai-documents
  dynamodb:
    endpoint: http://localstack:4566
    document-table: lexygraphai-documents
    chunk-table: lexygraphai-document-chunks
    collection-table: lexygraphai-collections
    procedure-table: lexygraphai-procedures
    workflow-table: lexygraphai-workflows

# Document service specific configuration
document:
  storage:
    type: s3  # Use S3 even in dev for consistency with production

# Integration with other services
service:
  text-processing:
    url: http://text-processing-service:8083/api/v1
  workflow:
    url: http://workflow-service:8084/api/v1

# Logging - more verbose in development
logging:
  level:
    root: INFO
    com.lexygraphai: DEBUG
    org.springframework.web: DEBUG
    com.amazonaws: DEBUG
    software.amazon.awssdk: DEBUG

# Security - more permissive CORS in development
spring:
  # For simplified authentication in development environment
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-auth.lexygraphai.com/.well-known/jwks.json
