# Server configuration
server:
  port: 8082
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

# Spring configuration
spring:
  application:
    name: document-service
  
  # Disable default database
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  
  # File upload limits
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# AWS Configuration
aws:
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket: ${S3_BUCKET_NAME:lexygraphai-documents}
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:http://localstack:4566}
    document-table: ${DOCUMENT_TABLE:lexygraphai-documents}
    chunk-table: ${CHUNK_TABLE:lexygraphai-document-chunks}
    collection-table: ${COLLECTION_TABLE:lexygraphai-collections}
    procedure-table: ${PROCEDURE_TABLE:lexygraphai-procedures}
    workflow-table: ${WORKFLOW_TABLE:lexygraphai-workflows}

# Document service specific configuration
document:
  storage:
    type: s3
  processing:
    chunk-size: 2000
    chunk-overlap: 200
    auto-summarize: true

# Security configuration
security:
  jwt:
    secret: ${JWT_SECRET:lexygraphai-document-service-jwt-secret-key-for-signing-tokens}
    expiration: 86400000  # 24 hours in milliseconds

# Integration with other services
service:
  text-processing:
    url: ${TEXT_PROCESSING_SERVICE_URL:http://text-processing-service:8083/api/v1}
  workflow:
    url: ${WORKFLOW_SERVICE_URL:http://workflow-service:8084/api/v1}

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  packages-to-scan: com.lexygraphai.document.controller

# Logging configuration
logging:
  level:
    root: INFO
    com.lexygraphai: DEBUG
    com.amazonaws: WARN
    software.amazon.awssdk: WARN
