version: '3.8'

services:
  # Spring Boot Document Service
  document-service:
    build:
      context: ./services/document-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - S3_ENDPOINT=http://localstack:4566
      - SQS_ENDPOINT=http://localstack:4566
      - RAW_BUCKET=docproc-raw-documents-dev
      - PROCESSED_BUCKET=docproc-processed-documents-dev
      - DOCUMENTS_TABLE=documents-dev
      - COLLECTIONS_TABLE=document-collections-dev
      - DOC_PROCESSING_TABLE=document-processing-dev
      - DOCUMENT_PARSER_QUEUE=http://localstack:4566/000000000000/document-parser-queue
      - OCR_PROCESSING_QUEUE=http://localstack:4566/000000000000/ocr-processing-queue
      - TEXT_PROCESSING_QUEUE=http://localstack:4566/000000000000/text-processing-queue
      - SUMMARIZER_QUEUE=http://localstack:4566/000000000000/summarizer-queue
      - AZURE_CV_ENDPOINT=${AZURE_CV_ENDPOINT}
      - AZURE_CV_KEY=${AZURE_CV_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AUTH_JWT_ISSUER=https://api.supabase.io
      - AUTH_JWT_JWK_SET_URI=https://api.supabase.io/.well-known/jwks.json
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080
    depends_on:
      - localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - docproc-network

  # Document Parser Service
  document-parser:
    build:
      context: ./services/document-parser
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ENDPOINT_URL=http://localstack:4566
      - DOCUMENTS_TABLE=documents-dev
      - DOC_PROCESSING_TABLE=document-processing-dev
      - TEXT_PROCESSING_QUEUE=http://localstack:4566/000000000000/text-processing-queue
      - OCR_PROCESSING_QUEUE=http://localstack:4566/000000000000/ocr-processing-queue
      - RAW_DOCUMENTS_BUCKET=docproc-raw-documents-dev
      - PROCESSED_DOCUMENTS_BUCKET=docproc-processed-documents-dev
    depends_on:
      - localstack
    networks:
      - docproc-network
    command: ["python", "-m", "awslambdaric", "app.lambda_handler"]

  # OCR Service
  ocr-service:
    build:
      context: ./services/ocr-service
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ENDPOINT_URL=http://localstack:4566
      - DOCUMENTS_TABLE=documents-dev
      - DOC_PROCESSING_TABLE=document-processing-dev
      - TEXT_PROCESSING_QUEUE=http://localstack:4566/000000000000/text-processing-queue
      - RAW_DOCUMENTS_BUCKET=docproc-raw-documents-dev
      - PROCESSED_DOCUMENTS_BUCKET=docproc-processed-documents-dev
      - AZURE_CV_ENDPOINT=${AZURE_CV_ENDPOINT}
      - AZURE_CV_KEY=${AZURE_CV_KEY}
    depends_on:
      - localstack
    networks:
      - docproc-network
    command: ["python", "-m", "awslambdaric", "app.lambda_handler"]

  # Text Processing Service
  text-processing:
    build:
      context: ./services/text-processing
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ENDPOINT_URL=http://localstack:4566
      - DOCUMENTS_TABLE=documents-dev
      - DOC_PROCESSING_TABLE=document-processing-dev
      - SUMMARIZER_QUEUE=http://localstack:4566/000000000000/summarizer-queue
      - PROCESSED_DOCUMENTS_BUCKET=docproc-processed-documents-dev
    depends_on:
      - localstack
    networks:
      - docproc-network
    command: ["python", "-m", "awslambdaric", "app.lambda_handler"]

  # Summarizer Service
  summarizer:
    build:
      context: ./services/summarizer
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ENDPOINT_URL=http://localstack:4566
      - DOCUMENTS_TABLE=documents-dev
      - DOC_PROCESSING_TABLE=document-processing-dev
      - PROCESSED_DOCUMENTS_BUCKET=docproc-processed-documents-dev
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - localstack
    networks:
      - docproc-network
    command: ["python", "-m", "awslambdaric", "app.lambda_handler"]

  # LocalStack for AWS services simulation
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./infrastructure/localstack:/docker-entrypoint-initaws.d
      - ./infrastructure/localstack/data:/tmp/localstack/data
    networks:
      - docproc-network

networks:
  docproc-network:
    driver: bridge
