services:
  # Chunker Service (FastAPI/Python)
  chunker-service:
    build:
      context: ./chunker-service
      dockerfile: Dockerfile
    # Espone la porta alla rete interna di Docker, consentendo al Document Service di connettersi.
    expose:
      - '8000'
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    healthcheck:
      # L'endpoint /health è stato aggiunto al codice Python per il controllo dello stato.
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # API Gateway (Spring Boot)
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVICES_DOCUMENT_SERVICE_URL=http://document-service:8000
      - SERVICES_EXTRACTION_AGENT_URL=http://extraction-agent:8001
      - SERVICES_SEARCH_AGENT_URL=http://search-agent:8002
      - SERVICES_GENERATION_AGENT_URL=http://generation-agent:8003
      - SERVICES_ORCHESTRATION_SERVICE_URL=http://orchestration-service:8005
    networks:
      - app-network
    depends_on:
      document-service:
        condition: service_healthy
      extraction-agent:
        condition: service_healthy
      search-agent:
        condition: service_healthy
      generation-agent:
        condition: service_healthy
      orchestration-service:
        condition: service_healthy
    healthcheck:
      test:
        ['CMD', 'wget', '--spider', '-q', 'http://localhost:8080/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s

  # Document Service (FastAPI/Python)
  document-service:
    build:
      context: ./document-service
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Extraction Agent (FastAPI/Python + Transformers - CPU optimized)
  extraction-agent:
    build:
      context: ./extraction-agent
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DOCUMENT_SERVICE_URL=http://api-gateway:8080
      - TORCH_NUM_THREADS=1
      - OMP_NUM_THREADS=1
    networks:
      - app-network
    depends_on:
      document-service:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8001/health']
      interval: 60s
      timeout: 45s
      retries: 2
      start_period: 180s # Allow time for model loading
    # Optimized resource limits for CPU inference
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # Search Agent (FastAPI/Python - Lightweight)
  search-agent:
    build:
      context: ./search-agent
      dockerfile: Dockerfile
    ports:
      - '8002:8002'
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8002/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    # Lightweight resource allocation
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Generation Agent (FastAPI/Python + Gemini - Lightweight)
  generation-agent:
    build:
      context: ./generation-agent
      dockerfile: Dockerfile
    ports:
      - '8003:8003'
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DOCUMENT_SERVICE_URL=http://document-service:8000
    networks:
      - app-network
    depends_on:
      document-service:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8003/health']
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s
    # Lightweight resource allocation since it uses external Gemini API
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Orchestration Service (FastAPI/Python + Gemini - AI Legal Assistant)
  orchestration-service:
    build:
      context: ./orchestration-service
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DOCUMENT_SERVICE_URL=http://document-service:8000
      - EXTRACTION_AGENT_URL=http://extraction-agent:8001
      - SEARCH_AGENT_URL=http://search-agent:8002
      - GENERATION_AGENT_URL=http://generation-agent:8003
    ports:
      - '8005:8005'
    networks:
      - app-network
    depends_on:
      document-service:
        condition: service_healthy
      extraction-agent:
        condition: service_healthy
      search-agent:
        condition: service_healthy
      generation-agent:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8005/health']
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s
    # Lightweight resource allocation for orchestration logic
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Frontend (React/Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8080
    ports:
      - '3000:80'
    networks:
      - app-network
    depends_on:
      - api-gateway
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    mem_limit: 2g
    cpus: 2
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:80/']
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  document-data:
    driver: local
