services:
  # Chunker Service (FastAPI/Python)
  chunker-service:
    build:
      context: ./chunker-service
      dockerfile: Dockerfile
    expose:
      - '8000'
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
