version: '3.8'

services:
  # Core infrastructure services
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,sqs,lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./init-localstack:/docker-entrypoint-initaws.d
      - ./localstack-data:/tmp/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lexygraphlab-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  document-service:
    build:
      context: ./document-service
      dockerfile: Dockerfile
    container_name: document-service
    ports:
      - "8080:8080"
    depends_on:
      - localstack
    env_file:
      - ./env.dev.yml
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    networks:
      - lexygraphlab-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - document-service
    env_file:
      - ./env.dev.yml
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DOCUMENT_SERVICE_URL=http://document-service:8080
    networks:
      - lexygraphlab-network

  # Processing microservices
  document-parser-service:
    build:
      context: ./document-parser-service
      dockerfile: Dockerfile
    container_name: document-parser-service
    depends_on:
      - localstack
    env_file:
      - ./env.dev.yml
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./document-parser-service:/app
    networks:
      - lexygraphlab-network
    command: python -u app.py  # -u for unbuffered output

  ocr-service:
    build:
      context: ./ocr-service
      dockerfile: Dockerfile
    container_name: ocr-service
    depends_on:
      - localstack
    env_file:
      - ./env.dev.yml
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./ocr-service:/app
    networks:
      - lexygraphlab-network
    command: python -u app.py

  text-processing-service:
    build:
      context: ./text-processing-service
      dockerfile: Dockerfile
    container_name: text-processing-service
    depends_on:
      - localstack
    env_file:
      - ./env.dev.yml
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./text-processing-service:/app
    networks:
      - lexygraphlab-network
    command: python -u app.py

  summarizer-service:
    build:
      context: ./summarizer-service
      dockerfile: Dockerfile
    container_name: summarizer-service
    depends_on:
      - localstack
    env_file:
      - ./env.dev.yml
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./summarizer-service:/app
    networks:
      - lexygraphlab-network
    command: python -u app.py

  # SQS Message processor (simulates Lambda trigger for local dev)
  sqs-processor:
    build:
      context: ./sqs-processor
      dockerfile: Dockerfile
    container_name: sqs-processor
    depends_on:
      - localstack
      - document-parser-service
      - ocr-service
      - text-processing-service
      - summarizer-service
    env_file:
      - ./env.dev.yml
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PARSER_SERVICE_URL=http://document-parser-service:5000
      - OCR_SERVICE_URL=http://ocr-service:5000
      - TEXT_PROCESSING_SERVICE_URL=http://text-processing-service:5000
      - SUMMARIZER_SERVICE_URL=http://summarizer-service:5000
    networks:
      - lexygraphlab-network

networks:
  lexygraphlab-network:
    driver: bridge
