apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - image: geekers/frontend
      name: frontend
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"
