openapi: 3.0.3
info:
  title: Agent Management Service API
  description: API for managing and invoking AWS Bedrock agents
  version: 1.0.0
servers:
  - url: https://api.lexygraphai.com/api/v1
    description: Production server
  - url: http://localhost:8083/api/v1
    description: Local development

tags:
  - name: agents
    description: Agent operations

paths:
  /agents:
    get:
      summary: List available agents
      description: Get a list of all available agents
      operationId: listAgents
      tags:
        - agents
      security:
        - bearerAuth: []
      parameters:
        - name: type
          in: query
          schema:
            type: string
            enum: [EXTRACTION, GENERATION, FORM_FILLING, ORCHESTRATION]
          description: Filter by agent type
      responses:
        '200':
          description: List of agents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Agent'
        '401':
          description: Unauthorized

  /agents/{agentId}:
    get:
      summary: Get agent details
      description: Get detailed information about a specific agent
      operationId: getAgent
      tags:
        - agents
      security:
        - bearerAuth: []
      parameters:
        - name: agentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Agent details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agent'
        '404':
          description: Agent not found

  /agents/custom:
    post:
      summary: Create custom agent
      description: Create a new custom agent based on a base agent type
      operationId: createCustomAgent
      tags:
        - agents
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomAgentRequest'
      responses:
        '201':
          description: Custom agent created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agent'
        '400':
          description: Invalid input

  /agents/invoke:
    post:
      summary: Invoke an agent
      description: Execute an agent with user prompt and optional document references
      operationId: invokeAgent
      tags:
        - agents
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvokeAgentRequest'
      responses:
        '200':
          description: Execution result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentResponse'
        '404':
          description: Agent or document not found
        '500':
          description: Agent execution failed

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Agent:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        type:
          type: string
          enum: [EXTRACTION, GENERATION, FORM_FILLING, ORCHESTRATION]
        isCustom:
          type: boolean
        baseType:
          type: string
          enum: [EXTRACTION, GENERATION, FORM_FILLING, ORCHESTRATION]
          description: Base agent type (for custom agents)
        customPrompt:
          type: string
          description: Custom prompt template (for custom agents)
        createdAt:
          type: string
          format: date-time

    CreateCustomAgentRequest:
      type: object
      required:
        - name
        - baseType
        - customPrompt
      properties:
        name:
          type: string
          description: Name for the custom agent
        description:
          type: string
          description: Description of the agent's purpose
        baseType:
          type: string
          enum: [EXTRACTION, GENERATION, FORM_FILLING, ORCHESTRATION]
          description: Type of base agent to customize
        customPrompt:
          type: string
          description: Custom prompt template to guide the agent

    InvokeAgentRequest:
      type: object
      required:
        - agentId
        - prompt
      properties:
        agentId:
          type: string
          description: ID of the agent to invoke (can be system or custom agent ID)
        prompt:
          type: string
          description: User prompt to guide the agent's task
        documentIds:
          type: array
          items:
            type: string
          description: Optional list of document IDs to process

    AgentResponse:
      type: object
      properties:
        executionId:
          type: string
        agentId:
          type: string
        result:
          type: string
          description: Output from the agent
        documentIds:
          type: array
          items:
            type: string
          description: Document IDs used in this execution
        timestamp:
          type: string
          format: date-time
