openapi: 3.0.3
info:
  title: Orchestrator Service API
  description: Multi-agent orchestration and coordination service
  version: 1.0.0

paths:
  /api/v1/orchestrator/plan:
    post:
      summary: Create execution plan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                documentIds:
                  type: array
                  items:
                    type: string
                userId:
                  type: string
                projectId:
                  type: string
              required: [prompt, documentIds, userId, projectId]
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  planId:
                    type: string
                  strategy:
                    type: string
                  estimatedSteps:
                    type: integer

  /api/v1/orchestrator/plan/{plan_id}/confirm:
    post:
      summary: Confirm or modify plan
      parameters:
        - name: plan_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                confirmed:
                  type: boolean
                additionalInstructions:
                  type: string
              required: [confirmed]
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  planId:
                    type: string
                  status:
                    type: string
                  updatedStrategy:
                    type: string

  /api/v1/orchestrator/execute:
    post:
      summary: Execute confirmed plan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                planId:
                  type: string
              required: [planId]
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  executionId:
                    type: string
                  status:
                    type: string

  /api/v1/orchestrator/status/{execution_id}:
    get:
      summary: Get execution status
      parameters:
        - name: execution_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  executionId:
                    type: string
                  status:
                    type: string
                  progress:
                    type: object
                    properties:
                      completedTasks:
                        type: integer
                      totalTasks:
                        type: integer
                  agentResults:
                    type: array
                    items:
                      type: object
                      properties:
                        agentId:
                          type: string
                        taskId:
                          type: string
                        response:
                          type: string
                        completedAt:
                          type: string
                  finalSummary:
                    type: string
