server:
  port: 8005

agents:
  extraction: ${SERVICES_EXTRACTION_AGENT_URL:http://extraction-agent:8001}
  search: ${SERVICES_SEARCH_AGENT_URL:http://search-agent:8002}

spring:
  main:
    web-application-type: reactive