apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: geekers/webapp2
          imagePullPolicy: Always
          name: webapp
          env:
            - name: LOGIC_API_URL
              value: "http://logic"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
