server:
  port: 8080
  servlet:
    context-path: /v1

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# Production environment configuration
RAW_BUCKET: arn:aws:s3:::valis-documents-raw
DOCUMENTS_TABLE: valis-documents
COLLECTIONS_TABLE: valis-document-collections
DOC_PROCESSING_TABLE: valis-document-processing
OCR_QUEUE: arn:aws:sqs:eu-central-1:078652648484:valis-documents-ocr-queue
TEXT_PROCESSING_QUEUE: arn:aws:sqs:eu-central-1:078652648484:valis-documents-text-processing-queue
SUMMARIZER_QUEUE: arn:aws:sqs:eu-central-1:078652648484:valis-documents-summarizer-queue
PARSER_QUEUE: arn:aws:sqs:eu-central-1:078652648484:valis-documents-parser-queue

# Auth configuration for Supabase
auth:
  jwt:
    issuer: https://sjfdkgzmjaasjtavuhfu.supabase.co
    jwk-set-uri: https://sjfdkgzmjaasjtavuhfu.supabase.co/auth/v1/jwks

# AWS configuration
aws:
  region: eu-central-1

# Logging configuration
logging:
  level:
    com.docprocessing: INFO
    org.springframework: WARN
